# Credit for this build setup goes to Dan Foreman-Mackey (github.com/dfm)

sudo: false

install:
    - source .ci/install.sh

script:
    - py.test -v -s
    - source .ci/build.sh

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
        source .ci/upload.sh
    fi
